---
name: "Display test"

on:
  workflow_dispatch:

run-name: Deploy - ${{ github.ref_name[0:7] }}

jobs:
  display_test:
    runs-on: ubuntu-latest
    steps:
      - name: test display
        shell: bash
        run: |
          echo "::notice title=Selected chart::kube-system"
          echo "::notice ::Selected chart 'kube-system'"
