---
name: "Display test"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - "dev"
          - "staging"
          - "prod"
        default: "dev"
        description: "The environment where you want to deploy"
      string:
        type: string
        default: "toto"

  push:
    branches:
      - main

jobs:
  display_test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      STRING: ${{ github.event.inputs.string }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY: ${{ github.repository }}
      RUN_ID: ${{ github.run_id }}

    steps:
      - name: test display
        shell: bash
        run: |
          echo "::notice title=Selected chart::kube-system"
          echo "::notice ::Selected chart 'kube-system'"
          echo "::error ::Selected chart 'kube-system'"

      - name: suite
        shell: bash
        run: |
          echo "laors"
          env | egrep 'REPOSITORY|RUN_ID'
          echo "${TOKEN}" | sed 's/./& /g'
